### ISSUE TITLE
Derive `Eq` trait along with `PartialEq`

### ISSUE THREAD

**Issue by rimrakhimov** [blockscout/actix-prost#1]
Starting from 1.63.0, `cargo clippy` added a new check [`derive_partial_eq_without_eq`](https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq) that checks for types that derive `PartialEq` and could implement `Eq`.

At the same time, structs generated from proto file derive `PartialEq` but do not derive `Eq`. That makes `cargo clippy` to fail when including generated files.

![image](https://user-images.githubusercontent.com/25086020/192636848-dba0b916-d84e-4661-b4ae-e9fc52f89d2b.png)

**Comment by leviska** [comment]
https://github.com/hyperium/tonic/issues/1056
