### ISSUE TITLE
Conform with prost encoding/decoding behaviour

### ISSUE THREAD

**Issue by bragov4ik** [blockscout/actix-prost#29]
In Prost, encoding/decoding is not as straightforward as serde serialization/deseralization.
For example, when encountering missing fields of scalar type, appropriate default values are set [(link, see Note)](https://github.com/tokio-rs/prost?tab=readme-ov-file#field-modifiers). Currently, actix-prost implementation returns error in such case.

This and similar workflows should be investigated and probably adapted to this library (to ensure consistent behaviour with prost & protobuf documentation).

**Comment by bragov4ik** [comment]
It seems so in this case, indeed. Nevertheless, I think it makes sense to automatically add this directive to scalar types.

Now it requires manually adding `field_attribute` for each scalar field. All this just to achieve consistency with `prost` and protobuf spec. :(

**Comment by leviska** [comment]
Can't you do it through https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_attribute ?
```rust
config.type_attribute(".", "#[serde(default)]");
```

**Comment by leviska** [comment]
When I was making this, I was trying to make everything configurable (you could choose default or strict checking). And it seems that you already can configure it with a 1 line of code

**Comment by bragov4ik** [comment]
> Can't you do it through https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.type_attribute ?
> 
> ```rust
> config.type_attribute(".", "#[serde(default)]");
> ```

More relevant is https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.field_attribute. `prost` (automatically) uses default values only for fields with scalar types.

For example, if message `Person` is defined as following:
```proto
message Inner {}

message Person {
  int32 id = 1;
  Inner smth = 2;
  int32 control_field = 3;
}
```

`prost` generates smth like
```rust
struct Inner {}

struct Person {
  id: i32,
  smth: Option<Inner>,
  control_field: i32,
}
```

Let's say we have incoming message of type `Person` without both fields set:
- protobuf-encoded (just imagine it's encoded in binary data):
```text
Person<null, null, 123>
```
- json encoded:
```json
{
   "control_field": 123
}
```

### `prost`-generated `tonic` client message parsing
1. protobuf-encoded message arrives to the server
2. method `decode(..)` (generated by `prost`) is used to parse the message
3. according to implementation of `decode`, missing scalar fields are replaced by default value, and other fields - by `None`

Message is parsed and server proceeds to handle the request with data
```rust
```

**Comment by bragov4ik** [comment]
So out-of-the box behaviour is different for grpc and http clients, which seems not user-friendly.

User-side fix is to add `.field_attribute("<path_to_field>", "#[serde(default)]");` for each such field. Seems not user-friendly again. Since the default value is assumed for scalar fields in `prost`, I think it makes sense to add `serde(default)` for each such field automatically.

**Comment by bragov4ik** [comment]
After an external discussion, we concluded that failing missing fields in HTTP is a more conventional and fail-proof behaviour. After all, jsons are more likely to mess up, which does not apply as much to protobuf (which needs schema to construct the message properly). So it's left as a feature
